
from tests.spec import LinuxTestSpec
import os

def test_open_create(t: LinuxTestSpec):
    with t.make_program_and_run('root', 'root', umask=0o022) as child:
        child.open("/file0", os.O_CREAT, 0o777)
        child.open("/file1", os.O_WRONLY | os.O_TMPFILE, 0o777)
        child.open("/file2", os.O_CREAT | os.O_WRONLY, 0o777)
        child.open("/file3", os.O_RDONLY, 0o777)
        child.open("/file4", os.O_CREAT | os.O_RDWR, 0o777)
        child.open("/file5", os.O_RDONLY | os.O_CREAT, 0o777)
        child.open("/file6", os.O_RDONLY | os.O_TMPFILE, 0o777)
        child.open("/file7", os.O_RDWR | os.O_TMPFILE, 0o777)
        child.open("/file8", os.O_RDONLY | os.O_PATH | os.O_CREAT, 0o777)

def test_open_exists(t: LinuxTestSpec):
    t.make_file("/file0", "root", "root", 0o777)
    t.make_dir("/dir1", "root", "root", 0o777)
    t.make_dir("/dir2", "root", "root", 0o777)
    t.make_file("/file3", "root", "root", 0o777)
    t.make_dir("/dir4", "root", "root", 0o777)
    t.make_dir("/dir5", "root", "root", 0o777)
    t.make_dir("/dir6", "root", "root", 0o777)
    t.make_file("/file7", "root", "root", 0o777)
    t.make_file("/file8", "root", "root", 0o777)
    t.make_file("/file9", "root", "root", 0o777)
    t.make_file("/file10", "root", "root", 0o777)
    t.make_file("/file11", "root", "root", 0o777)
    t.make_file("/file12", "root", "root", 0o777)
    t.make_dir("/dir13", "root", "root", 0o777)
    t.make_dir("/dir14", "root", "root", 0o777)
    t.make_file("/file15", "root", "root", 0o777)
    with t.make_program_and_run('root', 'root', umask=0o022) as child:
        child.open("/file0", os.O_RDONLY | os.O_PATH | os.O_EXCL | os.O_CREAT, 0)
        child.open("/dir1", os.O_RDONLY, 0)
        child.open("/dir2", os.O_RDONLY | os.O_DIRECTORY, 0)
        child.open("/file3", os.O_RDONLY, 0)
        child.open("/dir4", os.O_WRONLY, 0)
        child.open("/dir5", os.O_RDONLY | os.O_PATH | os.O_CREAT, 0)
        child.open("/dir6", os.O_RDONLY | os.O_CREAT, 0)
        child.open("/file7", os.O_RDONLY | os.O_DIRECTORY, 0)
        child.open("/file8", os.O_RDONLY | os.O_EXCL, 0)
        child.open("/file9", os.O_RDONLY | os.O_CREAT, 0)
        child.open("/file10", os.O_WRONLY, 0)
        child.open("/file11", 0, 0)
        child.open("/file12", os.O_RDONLY | os.O_EXCL | os.O_CREAT, 0)
        child.open("/dir13", os.O_RDWR, 0)
        child.open("/dir14", os.O_PATH | os.O_WRONLY, 0)
        child.open("/file15", os.O_RDWR, 0)

def test_openat_create(t: LinuxTestSpec):
    t.make_dir("/dir", "root", "root", 0o777)
    with t.make_program_and_run('root', 'root', umask=0o022) as child:
        fd = child.open("/dir", os.O_DIRECTORY | os.O_RDONLY, 0)
        child.openat(fd, "file0", os.O_CREAT, 0o777)
        child.openat(fd, "file1", os.O_WRONLY | os.O_TMPFILE, 0o777)
        child.openat(fd, "file2", os.O_CREAT | os.O_WRONLY, 0o777)
        child.openat(fd, "file3", os.O_RDONLY, 0o777)
        child.openat(fd, "file4", os.O_CREAT | os.O_RDWR, 0o777)
        child.openat(fd, "file5", os.O_RDONLY | os.O_CREAT, 0o777)
        child.openat(fd, "file6", os.O_RDONLY | os.O_TMPFILE, 0o777)
        child.openat(fd, "file7", os.O_RDWR | os.O_TMPFILE, 0o777)
        child.openat(fd, "file8", os.O_RDONLY | os.O_PATH | os.O_CREAT, 0o777)

def test_openat_exists(t: LinuxTestSpec):
    t.make_dir("/dir", "root", "root", 0o777)
    t.make_file("/dir/file0", "root", "root", 0o777)
    t.make_dir("/dir/dir1", "root", "root", 0o777)
    t.make_dir("/dir/dir2", "root", "root", 0o777)
    t.make_file("/dir/file3", "root", "root", 0o777)
    t.make_dir("/dir/dir4", "root", "root", 0o777)
    t.make_dir("/dir/dir5", "root", "root", 0o777)
    t.make_dir("/dir/dir6", "root", "root", 0o777)
    t.make_file("/dir/file7", "root", "root", 0o777)
    t.make_file("/dir/file8", "root", "root", 0o777)
    t.make_file("/dir/file9", "root", "root", 0o777)
    t.make_file("/dir/file10", "root", "root", 0o777)
    t.make_file("/dir/file11", "root", "root", 0o777)
    t.make_file("/dir/file12", "root", "root", 0o777)
    t.make_dir("/dir/dir13", "root", "root", 0o777)
    t.make_dir("/dir/dir14", "root", "root", 0o777)
    t.make_file("/dir/file15", "root", "root", 0o777)
    with t.make_program_and_run('root', 'root', umask=0o022) as child:
        fd = child.open("/dir", os.O_DIRECTORY | os.O_RDONLY, 0)
        child.openat(fd, "file0", os.O_RDONLY | os.O_PATH | os.O_EXCL | os.O_CREAT, 0)
        child.openat(fd, "dir1", os.O_RDONLY, 0)
        child.openat(fd, "dir2", os.O_RDONLY | os.O_DIRECTORY, 0)
        child.openat(fd, "file3", os.O_RDONLY, 0)
        child.openat(fd, "dir4", os.O_WRONLY, 0)
        child.openat(fd, "dir5", os.O_RDONLY | os.O_PATH | os.O_CREAT, 0)
        child.openat(fd, "dir6", os.O_RDONLY | os.O_CREAT, 0)
        child.openat(fd, "file7", os.O_RDONLY | os.O_DIRECTORY, 0)
        child.openat(fd, "file8", os.O_RDONLY | os.O_EXCL, 0)
        child.openat(fd, "file9", os.O_RDONLY | os.O_CREAT, 0)
        child.openat(fd, "file10", os.O_WRONLY, 0)
        child.openat(fd, "file11", 0, 0)
        child.openat(fd, "file12", os.O_RDONLY | os.O_EXCL | os.O_CREAT, 0)
        child.openat(fd, "dir13", os.O_RDWR, 0)
        child.openat(fd, "dir14", os.O_PATH | os.O_WRONLY, 0)
        child.openat(fd, "file15", os.O_RDWR, 0)
